# Create a new release keystore and android/keystore.properties (backs up existing files).
# Usage (from repo root):
#   $env:JAVA_HOME = "F:\Program Files\Android\Android Studio\jbr"
#   .\android\scripts\create-release-keystore.ps1

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$keytool = Join-Path $env:JAVA_HOME 'bin\keytool.exe'
$keystoreRel = '..\mobile\obostores-release.keystore'
$keystorePath = [System.IO.Path]::GetFullPath((Join-Path (Join-Path $repoRoot 'android') $keystoreRel))
$propsPath = Join-Path $repoRoot 'android\keystore.properties'
$alias = 'obostores'

if (-not (Test-Path $keytool)) {
    Write-Error "Set JAVA_HOME first, e.g. `$env:JAVA_HOME = 'F:\Program Files\Android\Android Studio\jbr'"
}

Write-Host 'Create a NEW release keystore for Google Play signing.'
Write-Host 'Use one password (6+ characters) for both store and key.'
Write-Host ''

$pass = Read-Host 'Enter new keystore password'
$pass2 = Read-Host 'Confirm password'
if ($pass -ne $pass2) {
    Write-Error 'Passwords do not match.'
}
if ($pass.Length -lt 6) {
    Write-Error 'Password must be at least 6 characters.'
}

if (Test-Path $keystorePath) {
    $bak = "$keystorePath.bak-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
    Move-Item $keystorePath $bak -Force
    Write-Host "Backed up old keystore to: $bak"
}

$dname = 'CN=OBO Stores, OU=Mobile, O=obo soft, L=Islamabad, ST=ICT, C=PK'
& $keytool -genkey -v `
    -keystore $keystorePath `
    -alias $alias `
    -keyalg RSA `
    -keysize 2048 `
    -validity 10000 `
    -storepass $pass `
    -keypass $pass `
    -dname $dname

if ($LASTEXITCODE -ne 0) {
    Write-Error 'keytool failed.'
}

$propsContent = @"
# Auto-generated by create-release-keystore.ps1
storeFile=$keystoreRel
storePassword=$pass
keyAlias=$alias
keyPassword=$pass
"@

try {
    Set-Content -Path $propsPath -Value $propsContent -Encoding UTF8
} catch {
    $tempProps = "$propsPath.new"
    Set-Content -Path $tempProps -Value $propsContent -Encoding UTF8
    Write-Host "Could not overwrite $propsPath (file may be open in the editor)." -ForegroundColor Yellow
    Write-Host "Close keystore.properties, then run:" -ForegroundColor Yellow
    Write-Host "  Move-Item -Force '$tempProps' '$propsPath'" -ForegroundColor Yellow
    Write-Host "Or paste this into android/keystore.properties:" -ForegroundColor Yellow
    Write-Host $propsContent
    exit 1
}

Write-Host ''
Write-Host 'Created:' -ForegroundColor Green
Write-Host "  $keystorePath"
Write-Host "  $propsPath"
Write-Host ''
Write-Host 'Verify, then build:' -ForegroundColor Green
Write-Host '  .\android\scripts\verify-keystore.ps1'
Write-Host '  cd mobile'
Write-Host '  npm run android:bundleRelease'
