/**
 * One-off utility: merge incremental migrations into consolidated schema files.
 * Run: npx tsx scripts/merge-migrations.ts
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const migrationsDir = path.resolve(__dirname, '../migrations');
const archiveDir = path.join(migrationsDir, 'archive');

const CONSOLIDATED_PG = '001-consolidated-schema.sql';
const CONSOLIDATED_SQLITE = '001-consolidated-schema.sqlite.sql';

function listPostgresMigrations(): string[] {
  return fs
    .readdirSync(migrationsDir)
    .filter((f) => f.endsWith('.sql'))
    .filter((f) => !f.includes('.sqlite.sql'))
    .filter((f) => f !== CONSOLIDATED_PG)
    .sort();
}

function mergePostgres(): string {
  const files = listPostgresMigrations();
  const parts: string[] = [
    '-- =============================================================================',
    '-- MyShop consolidated schema (PostgreSQL)',
    '-- Generated by server/scripts/merge-migrations.ts — do not edit by hand.',
    `-- Merged from ${files.length} incremental migration files.`,
    '-- Fresh databases: run via npm run migrate (only this file is applied).',
    '-- Existing databases: legacy rows in schema_migrations skip this file automatically.',
    '-- =============================================================================',
    '',
  ];

  for (const file of files) {
    const sql = fs.readFileSync(path.join(migrationsDir, file), 'utf-8').trim();
    parts.push(
      `-- -----------------------------------------------------------------------------`,
      `-- Source: ${file}`,
      `-- -----------------------------------------------------------------------------`,
      sql,
      '',
    );
  }
  return parts.join('\n');
}

function mergeSqlite(): string {
  const pgFiles = listPostgresMigrations();
  const parts: string[] = [
    '-- =============================================================================',
    '-- MyShop consolidated schema (SQLite)',
    '-- Generated by server/scripts/merge-migrations.ts — do not edit by hand.',
    `-- Merged from ${pgFiles.length} incremental migration files (sqlite-specific where present).`,
    '-- =============================================================================',
    '',
  ];

  for (const file of pgFiles) {
    const sqliteFile = file.replace('.sql', '.sqlite.sql');
    const sqlitePath = path.join(migrationsDir, sqliteFile);
    const source = fs.existsSync(sqlitePath) ? sqliteFile : file;
    const sql = fs.readFileSync(path.join(migrationsDir, source), 'utf-8').trim();
    parts.push(
      `-- -----------------------------------------------------------------------------`,
      `-- Source: ${source}`,
      `-- -----------------------------------------------------------------------------`,
      sql,
      '',
    );
  }
  return parts.join('\n');
}

function archiveIncremental(): number {
  if (!fs.existsSync(archiveDir)) {
    fs.mkdirSync(archiveDir, { recursive: true });
  }
  let moved = 0;
  for (const file of listPostgresMigrations()) {
    const pgPath = path.join(migrationsDir, file);
    const sqliteFile = file.replace('.sql', '.sqlite.sql');
    const sqlitePath = path.join(migrationsDir, sqliteFile);

    fs.renameSync(pgPath, path.join(archiveDir, file));
    moved++;
    if (fs.existsSync(sqlitePath)) {
      fs.renameSync(sqlitePath, path.join(archiveDir, sqliteFile));
    }
  }
  return moved;
}

function main() {
  const pgSql = mergePostgres();
  const sqliteSql = mergeSqlite();

  fs.writeFileSync(path.join(migrationsDir, CONSOLIDATED_PG), pgSql, 'utf-8');
  fs.writeFileSync(path.join(migrationsDir, CONSOLIDATED_SQLITE), sqliteSql, 'utf-8');

  const moved = archiveIncremental();
  console.log(`Wrote ${CONSOLIDATED_PG} (${pgSql.length} chars)`);
  console.log(`Wrote ${CONSOLIDATED_SQLITE} (${sqliteSql.length} chars)`);
  console.log(`Archived ${moved} incremental migration(s) to migrations/archive/`);
}

main();
